spring:
  application:
    name: cms
  config:
    import: optional:file:.env[.properties]
  datasource:
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:5432}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:}
    database: ${DATABASE_NAME:cms}
    mode: ${DATABASE_MODE:disable}
    ssl: ${DATABASE_SSL:false}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME:}}
    to: ${MAIL_TO:korrawit.universal@gmail.com}

logging:
  level:
    "[org.springframework.boot.SpringApplication]": off
